server:
  port: 8887
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8086/eureka/
spring:
  application:
    name: config-server-local
  profiles:
    #使用本机配置文件
    active: native
  cloud:
    config:
      # 当使用复合环境时，重要的是所有repos都包含相同的标签。如果您有类似于上述的环境，并且使用标签master请求配置数据，但是SVN repo不包含称为master的分支，则整个请求将失败。
      label: master
      server:
        native:
          # 配置文件所在目录，classpath（类路径）和（系统文件路径） file两种
          searchLocations: file:///D:/workspace/SpringcloudConfig/respo
        # 将导致配置客户端的所有应用程序独立于自己的配置读取foo=bar-bar。（当然，应用程序可以以任何方式使用Config Server中的数据，因此覆盖不可强制执行，但如果它们是Spring Cloud Config客户端，则它们会提供有用的默认行为。）
        overrides:
          foo: bar-bar
        # 配置服务器附带运行状况指示器，检查配置的EnvironmentRepository是否正常工作。
        health:
          repositories:
            myservice:
              label: mylabel
            myservice-dev:
              name: myservice
              profiles: development