spring:
  application:
    name: openFeign
server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8086/eureka/
#      defaultZone: http://localhost:8087/eureka/,http://localhost:8088/eureka/
