spring:
  application:
    name: openFeign
server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8086/eureka/
feign:
  hystrix:
    enabled: true
# HystrixDashboard need
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /